apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels: 
   app: nginx
spec:
 replicas: 1
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
    labels:
     app: nginx
  spec:
    containers:
    - name: my-nginx
      image: nginx:alpine
      ports:
      - containerPort: 80         #The default port for nginx is 80. It can be changed if required.
        hostPort: 8080
   
